# Generated by Django 2.1 on 2018-11-12 11:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='About',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0.0004955401387512388),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photos',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sravanthi/climbon/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
