# Generated by Django 2.1 on 2018-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181112_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photos',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='About',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
