# Generated by Django 2.1 on 2018-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181112_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
