# Generated by Django 2.1 on 2018-11-13 15:54

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181113_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('photos', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sravanthi/Desktop/climbon/media/photos'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_on', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('event_link', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sravanthi/Desktop/climbon/media/photos'), upload_to=''),
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='images',
            field=models.ManyToManyField(to='dashboard.Image'),
        ),
    ]
