# Generated by Django 2.1 on 2018-11-14 08:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181113_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photos',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sravanthi/Desktop/climbon/media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
