# Generated by Django 2.1 on 2018-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='content',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
