# Generated by Django 2.1 on 2018-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181114_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_id', models.IntegerField()),
                ('date_time', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('venue', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=55)),
                ('Contact_Us', models.IntegerField()),
            ],
        ),
    ]
