# Generated by Django 2.1 on 2018-11-19 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_eventdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='group',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='venue',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdata',
            name='status',
            field=models.CharField(default='upcomping', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdata',
            name='venue_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='venue_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='venue_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='Contact_Us',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
