# Generated by Django 2.1 on 2018-11-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20181119_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='created',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='updated',
            field=models.CharField(max_length=25),
        ),
    ]
