# Generated by Django 2.1 on 2018-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_eventdata_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='created_id',
            field=models.CharField(max_length=255),
        ),
    ]
