# Generated by Django 2.1 on 2018-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20181119_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='Contact_Us',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
