# Generated by Django 2.1 on 2018-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20181119_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
