# Generated by Django 2.1 on 2018-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_eventdata_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
