# Generated by Django 2.1 on 2018-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_eventphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='highres_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='thumb_link',
            field=models.URLField(max_length=500),
        ),
    ]
