# Generated by Django 2.1 on 2018-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20181122_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='photo_link',
            field=models.URLField(max_length=500),
        ),
    ]
