# Generated by Django 2.1 on 2018-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20181122_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('press_description', models.TextField(blank=True, null=True)),
                ('press_photos', models.ImageField(blank=True, upload_to='media/photos/')),
            ],
        ),
    ]
