# Generated by Django 2.1 on 2018-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20181129_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photos',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
