# Generated by Django 2.1 on 2018-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20181129_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='https://maxcdn.icons8.com/app/uploads/2016/10/person_1.png', upload_to='media/photos/'),
            preserve_default=False,
        ),
    ]
