# Generated by Django 2.1 on 2018-11-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20181129_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
