# Generated by Django 2.1 on 2018-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_press_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('thumbnail_url', models.URLField(max_length=500)),
            ],
        ),
    ]
