# Generated by Django 2.1 on 2018-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
