# Generated by Django 2.1 on 2018-12-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20181205_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='html',
            field=models.CharField(max_length=8000),
        ),
    ]
