# Generated by Django 2.1 on 2018-12-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20181206_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='html',
            field=models.TextField(),
        ),
    ]
