# Generated by Django 2.1 on 2018-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20181206_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='shortcode',
            field=models.CharField(default='Bgffq9Ch8M8', max_length=1000),
            preserve_default=False,
        ),
    ]
